jwt:
  secret:
    key: 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk

spring:
  datasource:
    url: jdbc:mysql://week06-team-1.co1d2mlhpaa6.ap-northeast-2.rds.amazonaws.com:3306/week06db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 5509kong

# datasource:
# url: jdbc:h2:mem:week06
# username: sa
# password:

cloud:
  aws:
    s3:
      bucket: eunibucket
      credentials :
        access-key: AKIA4NNWYQWVSTBKLI6F
        secret-key: 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
        region:
          static: ap-northeast-2
          auto: false
          stack:
            auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR


